export const FETCH_ISSUE = 'FETCH_ISSUE'
export const FETCH_PROJ_BY_ISSUE = 'FETCH_PROJ_BY_ISSUE'
export const SET_ISUUE_ID = "SET_ISUUE_ID"
export const CREATE_ISSUE_PROJECT = "CREATE_ISSUE_PROJECT"  
export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE"
export const AUTH_FAIL = 'AUTH_FAIL'
export const CHECK_TOKEN_VALIDIDTY = 'CHECK_TOKEN_VALIDIDTY'
export const SIGN_IN_WITH_TWITTER = "SIGN_IN_WITH_TWITTER"
export const SIGN_IN_WITH_GIT = "SIGN_IN_WITH_GIT";
export const SIGN_OUT  = "SIGN_OUT";
export const FETCH_STARTED = "FETCH_STARTED"
export const UPDATE_ANSWER_WITH_IMAGE = "UPDATE_ANSWER_WITH_IMAGE"
export const CLEAR_ANSWER = "CLEAR_ANSWER";
export const CREATE_ISSUE_PROJECT_FAILED ="CREATE_ISSUE_PROJECT_FAILED"
export const CANCEL_PROJ_CREATION_ERROR = "CANCEL_PROJ_CREATION_ERROR"
export const CANCEL_PROJ_CREATION_SUCCESS = "CANCEL_PROJ_CREATION_SUCCESS"
export const FETCH_DETAILS_OF_EXPLAINED = "FETCH_DETAILS_OF_EXPLAINED"
export const DISPLAY_SCREEN_SHARE ="DISPLAY_SCREEN_SHARE"


//Tool related
export const SCREEN_SHARE = "screenShare"
export const DISPLAY_SCREEN_RECORD = "DISPLAY_SCREEN_RECORD"
export const SCREEN_RECORD ="screenRecord";
export const START_RECORDING = "START_RECORDING";
export const START_SHARING = "START_SHARING";
export const STOP_SHARING ="STOP_SHARING";
export const STOP_RECORDING = "STOP_RECORDING"
export const SET_VIDEO_BLOB = "SET_VIDEO_BLOB"
export const DISCARD_RECORD_CHANGES ="DISCARD_RECORD_CHANGES"